version: "3.9"
services:
  ui:
    build: ./ui/
  api:
    build: ./api/
    depends_on:
      - "mongo"
  admin:
    build: ./admin/
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    restart: always
